# Exercise: Create a movie recommender system (NLP)

In [1]:
import pandas as pd

In [2]:
# Read the movies dataset
df_movies = pd.read_csv('../data/tmdb_5000_movies.csv')
print(df_movies.shape)
df_movies.head()

(4803, 20)


budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [3]:
# Read the credits dataset
df_credits = pd.read_csv('../data/tmdb_5000_credits.csv')
print(df_credits.shape)
df_credits.head()

(4803, 4)


movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

## Building the recommender system solely based on their overview

In [4]:
# Select a genre, filter the movies dataset to only include movies with the selected genre
df_movies_selected = df_movies[df_movies['genres'].str.contains('Action')]
df_movies_selected

budget                                             genres  \
0     237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4     260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...         ...                                                ...   
4734          0  [{"id": 53, "name": "Thriller"}, {"id": 28, "n...   
4769          0  [{"id": 28, "name": "Action"}, {"id": 37, "nam...   
4772      31192  [{"id": 18, "name": "Drama"}, {"id": 28, "name...   
4778          0  [{"id": 28, "name": "Action"}, {"id": 18, "nam...   
4798     220000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   

                                          homepage      id  \
0                      http://www.avatarmovie.com/   19995   
1     http://disney.go.com/disneypictures/pirates/     285   
2      http://www.sonypictures.com/movies/spectre/  206647   
3               http://www.thedarkknightrises.com/   49026   
4             http://movies.disney.com/john-carter   49529   
...                                            ...     ...   
4734                                           NaN  270554   
4769                                           NaN   69382   
4772              http://downterrace.blogspot.com/   42151   
4778                                           NaN   38780   
4798                                           NaN    9367   

                                               keywords original_language  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4     [{"id": 818, "name": "based on novel"}, {"id":...                en   
...                                                 ...               ...   
4734                                                 []                en   
4769                                                 []                en   
4772  [{"id": 9826, "name": "murder"}, {"id": 10123,...                en   
4778  [{"id": 10022, "name": "rampage"}, {"id": 1454...                en   
4798  [{"id": 5616, "name": "united states\u2013mexi...                es   

                                original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
4734                                  Echo Dr.   
4769                   The Legend of God's Gun   
4772                              Down Terrace   
4778                                   Rampage   
4798                               El Mariachi   

                                               overview  popularity  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577   
1     Captain Barbossa, long believed to be dead, ha...  139.082615   
2     A cryptic message from Bond’s past sends him o...  107.376788   
3     Following the death of District Attorney Harve...  112.312950   
4     John Carter is a war-weary, former military ca...   43.926995   
...                                                 ...         ...   
4734  When their home security system malfunctions, ...    0.053755   
4769  A gun-slinging preacher returns to the debauch...    0.003582   
4772  After serving jail time for a mysterious crime...    1.330379   
4778  The boredom of small town life is eating Bill ...    7.101197   
4798  El Mariachi just wants to play his guitar and ...   14.269792   

                                   productio

In [5]:
df_movies_selected.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [6]:
# Select only the title and overview columns
df_movies_selected = df_movies_selected[['title', 'overview']]
df_movies_selected = df_movies_selected.reset_index(drop=True)
df_movies_selected = df_movies_selected[:-1]
df_movies_selected

title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
1148                              Penitentiary   
1149                                  Echo Dr.   
1150                   The Legend of God's Gun   
1151                              Down Terrace   
1152                                   Rampage   

                                               overview  
0     In the 22nd century, a paraplegic Marine is di...  
1     Captain Barbossa, long believed to be dead, ha...  
2     A cryptic message from Bond’s past sends him o...  
3     Following the death of District Attorney Harve...  
4     John Carter is a war-weary, former military ca...  
...                                                 ...  
1148  A hitchhiker named Martel Gordone gets in a fi...  
1149  When their home security system malfunctions, ...  
1150  A gun-slinging preacher returns to the debauch...  
1151  After serving jail time for a mysterious crime...  
1152  The boredom of small town life is eating Bill ...  

[1153 rows x 2 columns]

In [7]:
# Select the overview of the movies as the corpus
corpus = df_movies_selected['overview'].values.astype('U')
corpus

array(['In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
       'Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems.',
       'A cryptic message from Bond’s past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE.',
       ...,
       'A gun-slinging preacher returns to the debaucherous town of Playa Diablo seeking revenge from the notorious scorpion-venom drinking bandito El Sobero - lead outlaw and number one bad guy. El Sobero and his band of bad banditos are also returning to Playa Diablo seeking their own revenge against the town sheriff. With the Bounty Hunter dragging up slowly 

In [8]:
# Calculate the TF-IDF for each movie overview
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english', strip_accents='ascii', lowercase=True, analyzer='word')
tfidf_matrix = tfidf.fit_transform(corpus)
print(tfidf_matrix.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [9]:
tfidf.get_feature_names_out()

array(['00', '000', '007', ..., 'zorro', 'zula', 'zuzu'], dtype=object)

In [10]:
# Calculate the cosine similarity between the selected movie and all the other movies
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
print(cosine_sim)
print(cosine_sim.shape)

[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.02682269]
 [0.         0.         1.         ... 0.         0.         0.02623624]
 ...
 [0.         0.         0.         ... 1.         0.         0.02103135]
 [0.         0.         0.         ... 0.         1.         0.03149835]
 [0.         0.02682269 0.02623624 ... 0.02103135 0.03149835 1.        ]]
(1153, 1153)


In [11]:
# %pip install nbformat

In [18]:
# Plot the cosine similarity matrix
import plotly.express as px

fig = px.imshow(cosine_sim[:50, :50])
fig.show()

**The generated cosine similarity matrix is not that good, having very small similarity values** 

In [13]:
# Select only the row of index 4 (John Carter)
cosine_sim[4]

array([0.        , 0.02934359, 0.        , ..., 0.        , 0.01286513,
       0.        ])

In [14]:
# Print the top 5 most similar movies
import numpy as np
sim_scores = list(enumerate(cosine_sim[4]))
sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
sim_scores = sim_scores[1:6]
print(sim_scores)

movie_indices = [i[0] for i in sim_scores]
# movie_indices

df_movies_selected['title'].iloc[movie_indices]

[(540, 0.2122228117720198), (1097, 0.16845399623486831), (978, 0.11178050004220165), (210, 0.09516312200359398), (306, 0.08916910912665642)]


540                      Get Carter
1097    The Marine 4: Moving Target
978                       Desperado
210                     Rush Hour 2
306         Star Trek: Insurrection
Name: title, dtype: object

In [15]:
# Print the selected movies title and overview

for i in range(5):
    print(f"{df_movies_selected['title'].iloc[movie_indices[i]]} - {df_movies_selected['overview'].iloc[movie_indices[i]]}")

Get Carter - Remake of the Michael Caine classic. Jack Carter, a mob enforcer living in Las Vegas, travels back to his hometown of Seattle for his brother's funeral. During this visit, Carter realizes that the death of his brother was not accidental, but a murder. With this knowledge, Carter sets out to kill all those responsible.
The Marine 4: Moving Target - WWE Superstar Mike "The Miz" Mizanin returns as Jake Carter where he is assigned to protect a whistleblower who wishes to expose a corrupt military defence contractor. However, the military hires a heavily armed team of mercenaries to kill her and it's up to Carter to stop them at any cost.
Desperado - A gunslinger is embroiled in a war with a local drug runner.
Rush Hour 2 - It's vacation time for Carter as he finds himself alongside Lee in Hong Kong wishing for more excitement. While Carter wants to party and meet the ladies, Lee is out to track down a Triad gang lord who may be responsible for killing two men at the American E